### ISSUE TITLE
The file name must match the module name

### ISSUE THREAD

**Issue by AlexxMarkov** [riscv-steel/riscv-steel#13]
Hello.

What do you think about the same file and module names?
As now: `file: rvsteel-soc.v` and `module: rvsteel_soc`.
But I would like to see it like this: `file: rvsteel_soc.v` and `module: rvsteel_soc`.

Matching the names will avoid generating warnings in `verilator` by default.

**Comment by rafaelcalcada** [comment]
Hi Alexx, I just changed the names. Now they are in sneak_case, hope it fix all warnings ;)

**Comment by AlexxMarkov** [comment]
Thank you)
