### ISSUE TITLE
Implementing for new example

### ISSUE THREAD

**Issue by Aishwaryakr2024** [riscv-steel/riscv-steel#62]
Hello everyone,
In this page they have mentioned examples that is hello world program  and they  have used "libsteel.h" header but at last we need .hex file ,they showed using makefile I don't know how use and how to add makefile file for my own program but at the end we we will set a path of .hex file in Vivado so I have generated .hex file in linux using riscv-gnu-toolchain and I am giving the path for this, but in Viavdo it is not taking the .hex file from that path.
And I have one more doubt like in mcu instance in the Vivado should I change anything other than giving the path of .hex file as a parameter in the MEM_INIT_FILE ?

**Comment by rafaelcalcada** [comment]
Hello @Aishwaryakr2024, thanks for your question. If you are using Vivado, you have to add the `.hex` file to the design sources as well. Vivado only reads files that were added to the design sources.

You also need to set `CLOCK_FREQUENCY` to the frequency of your FPGA board's clock. The other parameters don't need to be changed.

I hope this information help you. Don't hesitate to ask more help if you need :)

**Comment by Aishwaryakr2024** [comment]
Hello, thank you for your reply and I will try in this way .
