### ISSUE TITLE
Maximum Operating Frequency

### ISSUE THREAD

**Issue by AbdulrahmanKH7** [riscv-steel/riscv-steel#63]
Hi,
I would like to know what is the maximum clock frequency achieved by the steel MCU?
Thank you very much!

**Comment by rafaelcalcada** [comment]
Hello.

The maximum frequency depends on a few things:

- if RISC-V Steel is implemented on an FPGA, in general, the better the FPGA, the greater the max frequency will be. I have implemented RISC-V Steel on a Xilinx Artix-7 FPGA and achieved 50MHz. Higher speeds can be obtained on newer Xilinx devices.
- if you use RISC-V Steel on an ASIC design, the max frequency will depend on the technology node (e.g. 180nm, 22nm, etc). The speed will likely be higher when compared to an FPGA fabricated using the same technology node. The current version of RISC-V Steel has never been taped out. 

Hope it answers your question

**Comment by AbdulrahmanKH7** [comment]
Yes it's clear now, thank you.
